### ISSUE TITLE
可否开放源代码？如果不行的话，请忽略。

### ISSUE THREAD

**Issue by ouerye** [ABSK495/Genshin_Paimon_Assistant#2]

**Comment by plumsky** [comment]
这个工具是用python写的，使用pyinstaller打包，剩下的自己google搞定吧。

**Comment by Alex-Beng** [comment]
> 这个工具是用python写的，使用pyinstaller打包，剩下的自己google搞定吧。

用的python3.12，目前的开源un-compiler没有支持的。需要手工反编译。

**Comment by Alex-Beng** [comment]
此外，这玩意有联网行为，如果没有源码的话，建议谨慎使用

**Comment by ABSK495** [comment]
源码是我全程手撸的，所以不开放，联网仅为检查当前网络时间，没有其他多余操作。还有当着我的面讨论反编译，挺牛逼的，希望不要再提一些没有价值的issue，issue仅为用户反馈bug和优化建议使用，如果觉得反馈慢可以加Q群827797041。此issue即刻起关闭。

**Comment by Alex-Beng** [comment]
乐

**Comment by ccjjfdyqlhy** [comment]
有意思，但是联网不是还有注册登录忘记密码以及人数查询的功能吗？
